version: "3.9"
services:
  drink_server:
    ports:
      - "8080:80"
    build:
      dockerfile: config/docker/Dockerfile
    volumes:
       - ./:/code
    container_name: drink_server

  drink_db:
    image: percona
    container_name: drink_db
    environment:
      MYSQL_ROOT_PASSWORD: drinkrootpw
      MYSQL_DATABASE: drinkdb
      MYSQL_USER: drinkuser
      MYSQL_PASSWORD: drinkpw
    ports:
      - "12345:3306"